# This is a basic workflow to help you get started with Actions

name: run_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: |
          pip install poetry
          make install
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 3c3e72d86be06612f76026a55598c21fb69c3ca93532c9c28b47c0c993cf41dd
        with:
          coverageCommand: poetry run pytest --cov=page_loader --cov-report xml
          debug: true